### ISSUE TITLE
Mkdirp 0.5.3 pushed to NPM as 1.0.3

### ISSUE THREAD

**Issue by Luaancz** [isaacs/node-mkdirp#12]
It seems that the recent fix of dependencies on obsolete version resulted in the NPM package for mkdirp.1.0.3 to actually contain the old 0.x version. And since it was pushed as 1.0.3, everyone's packages just got silently "updated" to the old, deprecated version :)

**Comment by Luaancz** [comment]
My bad, it's actually the 0.5.3 version as expected, though it also caused silent and completely automatic update of the package, which is a bit annoying. I'm not a big fan of yarn...

**Comment by isaacs** [comment]
I know of another package manager you can use ;)
