### ISSUE TITLE
serverless-dynamodb-local required the latest version of mkdir to resolve the npm audit issue

### ISSUE THREAD

**Issue by derricktang94** [isaacs/node-mkdirp#14]
│ Low                      │ Prototype Pollution                                          
│ Package              │ minimist                 
│ Patched in          │ >=0.2.1 <1.0.0 || >=1.2.3
│ Dependency of │ serverless-dynamodb-local [dev] 
│ Path                    │ serverless-dynamodb-local > dynamodb-localhost > mocha > mkdirp > minimist  
│ More info           │ https://npmjs.com/advisories/1179

**Comment by iamlockon** [comment]
+1 having this issue.

**Comment by isaacs** [comment]
You can either install version 1.x or 0.5.4 of mkdirp to avoid the minimist issue.
