### ISSUE TITLE
mkdirp failed to create dir if running on pm2 and create di on /mnt share directory (network dir)

### ISSUE THREAD

**Issue by rusliabdulgani** [isaacs/node-mkdirp#23]
Hi All,

I have an issue about run script mkdirp with this environment and condition: 

1. create dir on share directory (/mnt/<dir>) that mapping from another server (network dir sharing)
2. if i run node js app using nodemon it is run smoothly, but if i run node js on pm2 this cause error like this: 
`Change detected on path share/mobiledocument/mobile_apps/doc/1282/82088/2020/May/09/8887779000001420/200710 for app mobile-apps-server - restarting`
3. in this case i should run my node js server using background management like pm2, cannot using nodemon.

This is script for create dir: 
`mkdirp('./share/mobiledocument/mobile_apps/doc/${clientid}/${coyid}/${year}/${monthNow}/${day}/${cardNumber}/${hhmmss}/${file.originalname.split('-')[0]}/', (err) => {
        if (!err) {
            cb(null, './share/mobiledocument/mobile_apps/doc/${clientid}/${coyid}/${year}/${monthNow}/${day}/${cardNumber}/${hhmmss}/${file.originalname.split('-')[0]}/')
        } else {
          console.log('error create dir', err)
        }
      })
`

this directory --> share/mobiledocument is share folder that mount and mapping from another server, that mean i need root access to do this. 

How can i fix this?

**Comment by isaacs** [comment]
What version of mkdirp are you using?  What error are you getting?

**Comment by isaacs** [comment]
No response, closing.
