### ISSUE TITLE
Unexpected token ... on lib/opts-arg.js

### ISSUE THREAD

**Issue by nicolas-sapaig** [isaacs/node-mkdirp#25]
Hello,

I have an issue after update, what does the "..." is expected to ?

```
/data/jenkins/workspace/somewhere/node_modules/mkdirp/lib/opts-arg.js:7
    opts = { mode: 0o777, fs, ...opts }
                              ^^^
SyntaxError: Unexpected token ...
```

Thanks.

**Comment by okeul** [comment]
Hi,

I got the same issue, what did you do ?

**Comment by nicolas-sapaig** [comment]
> 
> 
> Hi,
> 
> I got the same issue, what did you do ?

https://github.com/isaacs/node-mkdirp/issues/10

I use grunt 1.0
