### ISSUE TITLE
mkdirp error

### ISSUE THREAD

**Issue by mxnxsh** [isaacs/node-mkdirp#26]
code:
var mkdirp = require('mkdirp');
    
mkdirp('/tmp/foo/bar/baz', function (err) {
    if (err){
        console.log(e);
    }else{
        console.log('we are good.')
    }
});

error:
TypeError: invalid options argument
    at optsArg (D:\web\node_modules\mkdirp\lib\opts-arg.js:13:11)
    at mkdirp (D:\web\node_modules\mkdirp\index.js:11:10)

**Comment by isaacs** [comment]
That code is for mkdirp 0.x, and you're using 1.0.  See [the docs](https://github.com/isaacs/node-mkdirp/blob/master/readme.markdown) for current usage.
