### ISSUE TITLE
 'return' outside of function

### ISSUE THREAD

**Issue by M-Rb3** [isaacs/node-mkdirp#38]
I got this error when I ran babel build command, any help is appreciated
`babel . --out-dir build
`
\mkdirp\bin\cmd.js: 'return' outside of function. (13:4)

  11 | if (argv.help) {
  12 |     fs.createReadStream(__dirname + '/usage.txt').pipe(process.stdout);
> 13 |     return;
     |     ^
  14 | }
  15 |
  16 | var paths = argv._.slice();

node_modules\@babel\parser\lib\index.js:14928:21) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'IllegalReturn',
  loc: Position { line: 13, column: 4, index: 313 },
  pos: [Getter/Setter]
}

**Comment by isaacs** [comment]
not related to mkdirp, afaict
