### ISSUE TITLE
Vulnerable dependency (indirect security issue)

### ISSUE THREAD

**Issue by davidz1337** [isaacs/node-mkdirp#46]
Hello maintainers,

I wanted to bring to your attention that after installing the package, I ran a vulnerability scan with vulert abom on the lock file and discovered that there are over 1 vulnerable dependency present. As this vulnerability can potentially impact the security of the entire project, I am unsure whether to report this under responsible disclosure.

For your reference, here is a link to the report of the package-lock file I scanned: https://vulert.com/vuln-scan/list/70b57a94-960f-46b5-b15a-787766023134

I recommend that we take immediate action to address these vulnerabilities and ensure the security of the project. Please let me know if you require any further information.

P.S. this is the lock file i scanned: https://github.com/isaacs/node-mkdirp/blob/main/package-lock.json

Thank you.

**Comment by isaacs** [comment]
Please do not post issues like this. I assume that you mean well, but this is unhelpful noise.

The semver redos is only relevant if `semver.parse()` is called on untrusted input, and as you can see from the lockfile, semver is only used as a development dependency anyway, as indicated by `"dev": true` on all instances of semver in the lockfile. This isn't going to be a problem, ever. If I do manage to DOS myself while running my tests, then I'm sure life will go on, and it'll be just fine.

Furthermore, most people working on node programs use npm to install their dependencies, which already prints alerts about known vulnerabilities. There's also a plethora of tools that will report about advisories in dependencies in lockfiles, with varying degrees of automation. Anyone who wants this information, already has it, right at their finger tips while they work on their projects.

I hope this pushback isn't too forceful. As I said, I'm sure you mean well. But a sea of well-meaning noise is still a sea of noise, and in the cacophony of modern internet life, it's a constant struggle to find peace and focus.
